### ISSUE TITLE
Seems there is a double "/" in the file name in cache folder...

### ISSUE THREAD

**Issue by wysow** [maximejobin/rocket-nginx#13]
Hello,

First of all thanks a lot for this really cool config file!

I just tried it and it seems that it generate a double `/` here https://github.com/maximejobin/rocket-nginx/blob/master/rocket-nginx.conf#L60

Here is a debug header:

```
x-rocket-nginx-file:/var/www/mysite.com/wp-content/cache/wp-rocket/mysite.com//2016/01/article-slug//index.html_gzip
```

The problem is in **mysite.com//2016** for me.

**Comment by maximejobin** [comment]
Does it cause a problem ?  If so, what problem ?  Do you have a working example to reproduce the problem ?

The fact that there are 2 `/` should not change anything.  It is used to get the right cache file to display.  It has nothing to do with the URL.  If a problem occurs in the URL, please report it.

**Comment by wysow** [comment]
Sure it seems to be working, but that sounds like a possible little doable optimization no?

**Comment by maximejobin** [comment]
No, it wouldn't be an optimization.  It may look like it but, depending on how the HTTP request is built, it could cause problems.  The fact that you see 2 `/` is because not all parts of the request are used. Nginx's configuration does not handle a lot functions to "trim" and validate strings.

A lot of code would need to be added to "solve" the double slash. In the end, it would add more confusion.

That said, glad you take a look at what's under the hood! :-) :+1:

**Comment by wysow** [comment]
OK nevermind then... Thanks for your answers.
