### ISSUE TITLE
trailing index.html

### ISSUE THREAD

**Issue by keksdestodes** [maximejobin/rocket-nginx#15]
Hi,

none of my files get cached and if i debug it i get the following header:

    curl -I http://www.domain.de/wp-content/uploads/2015/11/picture.jpg

Output: 

	HTTP/1.1 200 OK
	Server: nginx/1.8.0
	Date: Mon, 11 Jan 2016 21:40:26 GMT
	Content-Type: image/jpeg
	Content-Length: 106266
	Last-Modified: Sat, 14 Nov 2015 14:42:16 GMT
	Connection: keep-alive
	ETag: "56474848-19f1a"
	Expires: Thu, 31 Dec 2037 23:55:55 GMT
	Cache-Control: max-age=315360000
	X-Rocket-Nginx-Bypass: No
	X-Rocket-Nginx-Reason: File not cached
	X-Rocket-Nginx-File: /var/www/domain.de/wp-content/cache/wp-rocket/www.domain.de//wp-content/uploads/2015/11/picture.jpg/index.html

The File has always an index.html at the end. Is this a bug?

**Comment by maximejobin** [comment]
> none of my files get cached

What files are you checking ? Static files such as images are NOT cached by WP-Rocket. Why ? Because it would not be faster in any way to do so.  That is why you won't find it in the path you provided.

That said, Rocket-Nginx adds an `Expires` header to tell your browser to cache it locally for a really long period.  As we see in the header you posted, the browser's cache should expire in 2037, so it's working.

If you want to test a cached file, run the same query directly on a WordPress page. Example:

    curl -I http://www.domain.de/

    curl -I http://www.domain.de/contact

That should give a different output (if you did not tell WP-Rocket to NOT cache the page).
