### ISSUE TITLE
Not working on Plesk nginx

### ISSUE THREAD

**Issue by xpresservers** [maximejobin/rocket-nginx#18]
Hi,

I am trying to get it working on plesk based nginx. I copied all contents from rocket-nginx.conf file and pasted in nginx directives section in plesk panel at domain level. After applying the configuration my site stopped working and trying to download a random file each time with blank page. How we can get it working with plesk based nginx?

If you want then I can provide you temporary access on a temporary environment.

Regards

**Comment by maximejobin** [comment]
Are you using Nginx as a reverse proxy ?

**Comment by xpresservers** [comment]
Yes, this is how nginx works in plesk https://www.dropbox.com/s/9pxtpp6v5u4r5ei/Screenshot%202016-03-17%2019.53.39.png?dl=0. I am using PHP 7.0.4 as FPM

https://www.dropbox.com/s/jpqeby3184itb61/Screenshot%202016-03-17%2019.55.40.png?dl=0

**Comment by maximejobin** [comment]
Used that way, the script won't really help as it will only process static files (which is already done when you activate Nginx in Plesk).

There are maybe ways to tweak your configuration to make it work but, as I'm not a Plesk user, I have no clue what needs to be done.

**Comment by disa87** [comment]
Hi, i have the same problem.

the nginx configuration file, is not correct for plesk, there is an error:

root@localhost:/etc/nginx/plesk.conf.d/vhosts# nginx -t
nginx: [emerg] "set" directive is not allowed here in /etc/nginx/rocket-nginx/rocket-nginx.conf:17
nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by maximejobin** [comment]
What version of Nginx are you using ? (nginx -v)

Can you output your whole config file that calls rocket-nginx.conf ?

**Comment by disa87** [comment]
Hey this is the Nginx version: nginx/1.9.4
I got the file over: 
git clone https://github.com/maximejobin/rocket-nginx.git
and i don't change anything

**Comment by maximejobin** [comment]
> Can you output your whole config file **that calls rocket-nginx.conf** ?

**Comment by disa87** [comment]
Hello,

yes i have upload it.

http://www.filedropper.com/rocket-nginx

can not upload here.

**Comment by maximejobin** [comment]
I was **NOT** talking about rocket-nginx.conf.  I am talking about the file that INCLUDES Rocket-Nginx.

You can use pastebin (http://pastebin.com/) to paste the configuration. Thank you.

**Comment by xpresservers** [comment]
Here is Nginx conf file for vhost http://pastebin.com/kPYVYWhQ. Line 116 and 225 calls same file which is being generated by Plesk's builtin utility, And here is content of vhost_nginx.conf file

http://pastebin.com/qdvsCsLE

If you want to work with Plesk then I can create an account for you

**Comment by maximejobin** [comment]
Please review the way the installation should be done.  You cannot copy/paste the configuration anywhere you want.

Also, in your files, **I don't see the include for `rocket-nginx.conf`.**

**Comment by xpresservers** [comment]
I am not calling rocket-nginx.conf but using code from it in 2nd pastebin

**Comment by coadr** [comment]
Same, I need this to work as well on plesk.. Also for a lot of customers who use plesk panels to configure their hosting. Would be nice if there's the ability to get it working.

**Comment by Gamikoula** [comment]
so for me it is working fine. 

u have to create a file and name it rocket-nginx.conf in your nginx directory, add this code inside
https://github.com/maximejobin/rocket-nginx/blob/master/rocket-nginx.conf
in debian it is  /etc/nginx

and paste this line

# Rocket-Nginx configuration
include rocket-nginx.conf;

in Additional nginx directives of your domain. 

U have to deactivate static files by nginx. not needed then anymore because it will slow your website

thats it

**Comment by VicPT** [comment]
I did as the instructions... installed first Git (yum install git). Then I pasted "include rocket-nginx.conf;" in the additional nginx directives of my domain. I then set the debug to on and I have the following:

x-powered-by: PHP/7.0.9
x-powered-by: PleskLin
x-rocket-nginx-bypass: No
x-rocket-nginx-file: /var/www/vhosts/MYDOMAIN.com/httpdocs/wp-content/cache/wp-rocket/www.MYDOMAIN.com//folder1/folder2/websitefile//index-https.html_gzip
x-rocket-nginx-reason: File not cached

I am pretty sure the page is cached as the source file ends with the "like a rocket" frase.

Under the nginx/apache settings in plesk (plesk 12.5), I tried turning off and on "Smart static files processing", and also tried turning on "Serve static files directly by nginx" with the following default files active:
ac3 avi bmp bz2 css cue dat doc docx dts eot exe flv gif gz htm html ico img iso jpeg jpg js mkv mp3 mp4 mpeg mpg ogg pdf png ppt pptx qt rar rm svg swf tar tgz ttf txt wav woff woff2 xls xlsx zip

No matter what I did, I always get the result  x-rocket-nginx-bypass: No


Note: Using latest versions of Nginx, PHP7, Apache and Plesk.....in other words, no updates are available to do in Plesk.

Also to note, Nginx is running as a reverse proxy server in front of Apache and I have the following added in nginx.conf:

gzip on;
gzip_vary on;
gzip_proxied any;
gzip_comp_level 6;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_types image/svg+xml text/plain text/html text/xml text/css text/javascript application/xml application/xhtml+xml application/rss+xml application/javascript application/x-javascript application/x-font-ttf application/vnd.ms-fontobject font/opentype font/ttf font/eot font/otf;

#open file cache
open_file_cache max=1000 inactive=20s; 
open_file_cache_valid 60s;
open_file_cache_min_uses 2; 
open_file_cache_errors off;

**Comment by wilrevehl** [comment]
I'll be giving this a try soon in Plesk 12.5x soon as well. Will let you know if there's any configurations that need addressed with this OS to make it work.

**Comment by wilrevehl** [comment]
Update - it can work in Plesk, but has to be implemented at the domain settings level due to how Plesk creates a pseudo VPS sort of environment for each site. PLEASE NOTE: We are running PHP module as fast_cgi. PHP FPM would almost certainly require a different setup because mod rewrites work different in FPM. Anyway, assuming you're using fast_cgi (or this would probably work with little-to-no changes in the standard Apache PHP) Here's how: 

1. Add this rocket-nginx.conf script to your system conf folder for the domain. So /var/www/vhosts/system/yourfastsite.com/conf

2. In Plesk go to the Domain and click on Apache & nginx Settings. nginx should be set to Smart static file processing. DO NOT use Serve static files directly by nginx.

3. While on the same page, in the field where it says Additional nginx directives, enter the following: 

`proxy_buffer_size   128k;
proxy_buffers   4 256k;
proxy_busy_buffers_size   256k;
#proxy_read_timeout 600;

#if (!-e $request_filename){
	#	rewrite ^(.*)$ /index.php break;
	#}

	# enable gzip compression
	gzip on;
	gzip_min_length 1100;
	gzip_buffers 4 32k;
	gzip_types text/plain text/javascript application/javascript application/x-javascript text/xml text/css;
	gzip_vary on;
	# end gzip configuration
        # Use the path to your rocket_nginx.conf file
	include /var/www/vhosts/system/yourfastsite.com/conf/rocket_nginx.conf;`

That's the crux of it. 

You might need to reload nginx afterward, you can find some info here on that: http://www.cyberciti.biz/faq/howto-unix-linux-gracefully-reload-restart-nginx-webserver/ 

cheers

**Comment by wilrevehl** [comment]
Dah, github split that code block formatting - be sure to put everything from proxy_buffer_size down to include /var/www/... into the directive.

**Comment by sallida** [comment]
Hello,

I'm trying also to get the  Nginx conf of wp rocket work when using Apache and Nginx as reverse Proxy with Plesk Centos.

‪CentOS Linux 7.6.1810 (Core)‬ with Plesk Onyx 17.8.11 Update #66 

Apache/2.4.6 (CentOS)
nginx/1.16.1

**Htaccess File Apache:**

# BEGIN WP Rocket v3.3.7
# Use UTF-8 encoding for anything served text/plain or text/html
AddDefaultCharset UTF-8
# Force UTF-8 for a number of file formats
<IfModule mod_mime.c>
AddCharset UTF-8 .atom .css .js .json .rss .vtt .xml
</IfModule>
# FileETag None is not enough for every server.
<IfModule mod_headers.c>
Header unset ETag
</IfModule>
# Since we’re sending far-future expires, we don’t need ETags for static content.
# developer.yahoo.com/performance/rules.html#etags
FileETag None
<IfModule mod_alias.c>
<FilesMatch "\.(html|htm|rtf|rtx|txt|xsd|xsl|xml)$">
<IfModule mod_headers.c>
Header set X-Powered-By "WP Rocket/3.3.7"
Header unset Pragma
Header append Cache-Control "public"
Header unset Last-Modified
</IfModule>
</FilesMatch>
<FilesMatch "\.(css|htc|js|asf|asx|wax|wmv|wmx|avi|bmp|class|divx|doc|docx|eot|exe|gif|gz|gzip|ico|jpg|jpeg|jpe|json|mdb|mid|midi|mov|qt|mp3|m4a|mp4|m4v|mpeg|mpg|mpe|mpp|otf|odb|odc|odf|odg|odp|ods|odt|ogg|pdf|png|pot|pps|ppt|pptx|ra|ram|svg|svgz|swf|tar|tif|tiff|ttf|ttc|wav|wma|wri|xla|xls|xlsx|xlt|xlw|zip)$">
<IfModule mod_headers.c>
Header unset Pragma
Header append Cache-Control "public"
</IfModule>
</FilesMatch>
</IfModule>
# Expires headers (for better cache control)
<IfModule mod_expires.c>
	ExpiresActive on
	# Perhaps better to whitelist expires rules? Perhaps.
	ExpiresDefault                              "access plus 1 month"
	# cache.appcache needs re-requests in FF 3.6 (thanks Remy ~Introducing HTML5)
	ExpiresByType text/cache-manifest           "access plus 0 seconds"
	# Your document html
	ExpiresByType text/html                     "access plus 0 seconds"
	# Data
	ExpiresByType text/xml                      "access plus 0 seconds"
	ExpiresByType application/xml               "access plus 0 seconds"
	ExpiresByType application/json              "access plus 0 seconds"
	# Feed
	ExpiresByType application/rss+xml           "access plus 1 hour"
	ExpiresByType application/atom+xml          "access plus 1 hour"
	# Favicon (cannot be renamed)
	ExpiresByType image/x-icon                  "access plus 1 week"
	# Media: images, video, audio
	ExpiresByType image/gif                     "access plus 4 months"
	ExpiresByType image/png                     "access plus 4 months"
	ExpiresByType image/jpeg                    "access plus 4 months"
	ExpiresByType image/webp                    "access plus 4 months"
	ExpiresByType video/ogg                     "access plus 1 month"
	ExpiresByType audio/ogg                     "access plus 1 month"
	ExpiresByType video/mp4                     "access plus 1 month"
	ExpiresByType video/webm                    "access plus 1 month"
	# HTC files  (css3pie)
	ExpiresByType text/x-component              "access plus 1 month"
	# Webfonts
	ExpiresByType font/ttf                      "access plus 4 months"
	ExpiresByType font/otf                      "access plus 4 months"
	ExpiresByType font/woff                     "access plus 4 months"
	ExpiresByType font/woff2                    "access plus 4 months"
	ExpiresByType image/svg+xml                 "access plus 1 month"
	ExpiresByType application/vnd.ms-fontobject "access plus 1 month"
	# CSS and JavaScript
	ExpiresByType text/css                      "access plus 1 year"
	ExpiresByType application/javascript        "access plus 1 year"
</IfModule>
# Gzip compression
<IfModule mod_deflate.c>
# Active compression
SetOutputFilter DEFLATE
# Force deflate for mangled headers
<IfModule mod_setenvif.c>
<IfModule mod_headers.c>
SetEnvIfNoCase ^(Accept-EncodXng|X-cept-Encoding|X{15}|~{15}|-{15})$ ^((gzip|deflate)\s*,?\s*)+|[X~-]{4,13}$ HAVE_Accept-Encoding
RequestHeader append Accept-Encoding "gzip,deflate" env=HAVE_Accept-Encoding
# Don’t compress images and other uncompressible content
SetEnvIfNoCase Request_URI \
\.(?:gif|jpe?g|png|rar|zip|exe|flv|mov|wma|mp3|avi|swf|mp?g|mp4|webm|webp|pdf)$ no-gzip dont-vary
</IfModule>
</IfModule>
# Compress all output labeled with one of the following MIME-types
<IfModule mod_filter.c>
AddOutputFilterByType DEFLATE application/atom+xml \
		                          application/javascript \
		                          application/json \
		                          application/rss+xml \
		                          application/vnd.ms-fontobject \
		                          application/x-font-ttf \
		                          application/xhtml+xml \
		                          application/xml \
		                          font/opentype \
		                          image/svg+xml \
		                          image/x-icon \
		                          text/css \
		                          text/html \
		                          text/plain \
		                          text/x-component \
		                          text/xml
</IfModule>
<IfModule mod_headers.c>
Header append Vary: Accept-Encoding
</IfModule>
</IfModule>
<IfModule mod_mime.c>
AddType text/html .html_gzip
AddEncoding gzip .html_gzip
</IfModule>
<IfModule mod_setenvif.c>
SetEnvIfNoCase Request_URI \.html_gzip$ no-gzip
</IfModule>
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteCond %{HTTPS} on [OR]
RewriteCond %{SERVER_PORT} ^443$ [OR]
RewriteCond %{HTTP:X-Forwarded-Proto} https
RewriteRule .* - [E=WPR_SSL:-https]
RewriteCond %{HTTP:Accept-Encoding} gzip
RewriteRule .* - [E=WPR_ENC:_gzip]
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{QUERY_STRING} =""
RewriteCond %{HTTP:Cookie} !(wordpress_logged_in_.+|wp-postpass_|wptouch_switch_toggle|comment_author_|comment_author_email_) [NC]
RewriteCond %{REQUEST_URI} !^(/(.*)sitemap(.*).xml|/(.*)sitemap.xsl|/(.+/)?feed/?|/(?:.+/)?embed/|/(index\.php/)?wp\-json(/.*|$))$ [NC]
RewriteCond %{HTTP_USER_AGENT} !^(iPad|NexusTablet|SamsungTablet|HPTablet|AsusTablet|BlackBerryTablet|HTCtablet|MotorolaTablet|AcerTablet|ToshibaTablet|LGTablet|FujitsuTablet|LenovoTablet|DellTablet|SonyTablet|PhilipsTablet|HuaweiTablet|facebookexternalhit).* [NC]
RewriteCond "%{DOCUMENT_ROOT}/subdirectory/wp-content/cache/wp-rocket/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:WPR_SSL}.html%{ENV:WPR_ENC}" -f
RewriteRule .* "/subdirectory/wp-content/cache/wp-rocket/%{HTTP_HOST}%{REQUEST_URI}/index%{ENV:WPR_SSL}.html%{ENV:WPR_ENC}" [L]
</IfModule>
# END WP Rocket





Nginx Settings
- Proxy Mode on
- Smart static File processing on
- Serve Static Files directly by Nginx on
- Enable Nginx Caching on 


**Nginx additional directives:**

gzip on;
gzip_disable "MSIE [1-6]\\.(?!.*SV1)";
gzip_vary on;
gzip_proxied any;
gzip_comp_level 5;
gzip_buffers 16 8k;
gzip_http_version 1.1;
gzip_min_length 256;
gzip_types application/javascript application/rss+xml application/vnd.ms-fontobject application/x-font application/x-font-opentype application/x-font-otf application/x-font-truetype application/x-font-ttf application/x-javascript application/xhtml+xml application/xml font/opentype font/woff2 font/otf font/ttf image/svg+xml image/x-icon image/jpg image/jpeg image/png image/ico text/css text/javascript text/plain text/xml;
# Seec Headers - HTTP Strict Transport Security (HSTS)
add_header Strict-Transport-Security max-age=61536000;
# Sec Headers - Feature Policy
add_header Feature-Policy "microphone 'none'; camera 'none';";
# Nginx Expires
location ~* .(js|jpg|jpeg|gif|png|css|tgz|gz|rar|bz2|doc|pdf|ppt|tar|wav|bmp|rtf|swf|ico|flv|txt|woff|woff2|svg)$ {
	expires 10m;
	add_header Pragma "public";
	add_header Cache-Control "public";
}

Can someone point me in the right direction, please?

Thanks a lot!

Best regards
Sallida
