### ISSUE TITLE
Can be used with fastcgi?

### ISSUE THREAD

**Issue by timersys** [maximejobin/rocket-nginx#3]
Sorry I couldn't find a way to contact you so I opened a new ticket. 
Can this be or should be used with fastcgi cache for example or some other nginx cache system ?

Thanks!

**Comment by maximejobin** [comment]
"Can this be"... probably!

"Should this be"... I don't think so. Basically, the configuration asks Nginx to serve the static file directly (without using PHP-FPM and executing WP-Rocket to server the static file).  You should note that once Nginx reads a file on disk, it caches that static files in RAM.  The question is: what kind of caching would like to achieve that is not already done by Nginx ?

**Comment by timersys** [comment]
Thanks for your clarification.
Im just tying to achieve the best caching posible in my system that will allow me to serve as much concurrent users as possible.
I did an [easyengine](http://docs.rtcamp.com/easyengine/) install that brings memcache by default but wp rocket don't support it yet.
I always used w3 total cache with apc and varnish and now Im trying to get the best of wp rocket

**Comment by maximejobin** [comment]
The caching is different in W3TC as you can cache objects (which you can't do in WP-Rocket). I dropped W3TC for WP-Rocket because the configuration was a pain and I found several bugs that proved the product wasn't tested properly.

W3TC surely offers more options but it's also more complex to configure. You might want to ask yourself what is *really* needed for your website.

With Rocket-Nginx, you could shutdown PHP-FPM if all your pages are cached (once they are in cache, of course).  That will save you a lot of resource as Nginx was designed to be efficient with static files.
