### ISSUE TITLE
Nginx error log

### ISSUE THREAD

**Issue by Jason1976** [maximejobin/rocket-nginx#31]
Hey,

Something like this should be good (although I would first contact hosting provider):

/**********************************************

Hi Maxime,

I have one issue with my NGINX configuration. I am using WP Rocket and have implemented your settings. However I am getting the following errors in NGINX error log:

=========== error message ===========
2016/07/21 05:23:23 [warn] 21835#21835: *983 using uninitialized "rocket_file" variable, client: 52.1.31.247, server: appleme.club, request: "GET /feed/ HTTP/1.1″, host: "appleme.club"
2016/07/21 05:28:07 [warn] 21835#21835: *1100 using uninitialized "rocket_is_bypassed" variable, client: 195.2.219.97, server: appleme.club, request: "GET /feed/ HTTP/1.1″, host: "appleme.club"
2016/07/21 05:28:07 [warn] 21835#21835: *1100 using uninitialized "rocket_reason" variable, client: 195.2.219.97, server: appleme.club, request: "GET /feed/ HTTP/1.1″, host: "appleme.club"

Have you experienced similar issue with your configuration in the past? Do you have any suggestion? My pages are properly cached and everything seems to be ok, but these errors keep showing up in my error log.

**********************************************/

Additionally, you should add your host's answer, just to be sure it is not caused by some other settings inside NGINX configuration.

**Comment by maximejobin** [comment]
Hello,

I have not experimented the error log you are describing.  You are also the first person to report that. This does not mean your issue is invalid... but it might be related to something else.

The only valuable resource I found on the topic is this: https://www.ruby-forum.com/topic/4418580

Here is the interesting part:

> The "set" directive isn't something essential, and actually it is just a
directive from the rewrite module.

> See here how it works:
http://nginx.org/en/docs/http/ngx_http_rewrite_module.html

> It is evaluated on the rewrite phase of request processing.  Thus, if
the request is finalized before this phase, then your variable is left
uninitialized.

It could be caused by other directives you have in your configuration files.

**Comment by marsch** [comment]
am also exp. this error - still
