### ISSUE TITLE
Nginx as reverse proxy and rocket-nginx

### ISSUE THREAD

**Issue by Antieno** [maximejobin/rocket-nginx#8]
Hello Maxime,

Thanks very much for your code. It is in production with woocommerce and give to our shop the speed of a static website.

If I work with [hiawatha web server](https://www.hiawatha-webserver.org/) for security purpose, this one can't serve directly files in wp-rocket cache folder without calling php-fpm process. 
Same scenario with apache or other web server.

So, is it possible to use your script with nginx as reverse proxy ?

Best regards

**Comment by maximejobin** [comment]
Yes, it is totally possible.

That said, if you use Nginx as a reverse proxy, it is probably because you are using Apache.  Therefore, you wouldn't use PHP-FPM, right ?  Usually FPM is used when Nginx is used alone.

When you say "this one can't serve directly files in wp-rocket cache folder without calling php-fpm process.", does it mean they tweaked their configuration to serve every file (CSS, JS, images, ...) via FPM ?  If that's the case, this adds a lot of unnecessary overhead to your server.

Please add more details.
