### ISSUE TITLE
Security Headers Defined in Server Block

### ISSUE THREAD

**Issue by royashgit** [maximejobin/rocket-nginx#89]
Hi maxime

I am wondering if rocket-nginx interferes with headers i define in my server block. 

I have added:

```
server {

add_header Content-Security-Policy "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval';" always;
add_header X-Xss-Protection "1; mode=block" always;

}
```

But these don't seem to work.

**Comment by royashgit** [comment]
I am still using v1 btw. Is it better to upgrade to v2 ?

**Comment by maximejobin** [comment]
Yes it does impact what you setup.

The way Nginx works is that if you add headers in a "lower" block, it cancels what you added in a higher block.

You added headers at the `server` level and then I add headers  in `location` header. So instead of simply adding up everything or replacing part of what is already there, it cancels everything you put at the `server` level.

Fortunately, you can add these in the headers in the configuration file in version 2 of Rocket-Nginx!

**Comment by royashgit** [comment]
Ok I am looking at v2 now but still I am a bit confused.

1. Is it possible to add the headers directly to the default.conf file instead of the .ini - I don't understand how to translate the notation of my Content-Security-Policy to the .ini file. 

2. Even if I make changes to the .ini file, do I need to run the php rocket-parser.php again?

3. I am still not sure exactly where to place the security headers. As I understand, the default.conf has two places for cached and non-cached content. Do I need to write the headers twice?

4. This thread offers an alternative solution on where to place the headers. Will this be compatible with your script?

https://www.peterbe.com/plog/be-very-careful-with-your-add_header-in-nginx

Sorry for all the questions but I am sure you can understand this is important stuff! Thanks so much for all your help.

**Comment by royashgit** [comment]
So in a nutshell, I think I need to go with this method:

https://gist.github.com/april/577212e08101186f81b5ff682f35f7cf

And include the pokeinthe.io.conf which I will call "security.conf" to 3 different places in default.conf

location ~ /wp-content/cache/wp-rocket/.*html$ {.. }
location ~ /wp-content/cache/wp-rocket/.*_gzip$ {.. }
# Debug header (when file is not cached) - though I am not sure if it's needed (since I will also include security.conf in the server block)..

Am I right ? :)

**Comment by maximejobin** [comment]
To answer your question:

1. Do not alter the .conf file. Put everything in the ini file. Otherwise, you will lose your changes when you run the parser.

2. Yes, you need to run the parser to generate the file

3. You discovered a limitation with the statements you provided. I will mark this as en enhacement and will address this in the next version. Thank you for that!

4. The thread is explaining exactly what I was saying in my previous message.

In the end, I suggest you "manually" alter the generated .conf file until I release version 2.2.

**Comment by royashgit** [comment]
Yes I followed my method of including the security.conf in the abovementioned locations and everything works as expected..
